spring.application.name=sep-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sep
spring.datasource.username=sep
spring.datasource.password=sep
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect 
